//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUONGPHO
    {
        public DUONGPHO()
        {
            this.KHACHHANGs = new HashSet<KHACHHANG>();
            this.TIEUTHUs = new HashSet<TIEUTHU>();
        }
    
        public string MADP { get; set; }
        public string DUONGPHU { get; set; }
        public string TENDP { get; set; }
        public string TENHD { get; set; }
        public string MAKV { get; set; }
        public string MAPHUONG { get; set; }
        public string TENPHUONG { get; set; }
    
        public virtual PHUONG PHUONG { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        public virtual ICollection<TIEUTHU> TIEUTHUs { get; set; }
    }
}
