//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class KG_ClockRecordEntities : DbContext
    {
        
        public KG_ClockRecordEntities()
            : base("name=KG_ClockRecordEntities")
        {
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 0;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<t_Accountant_Files> t_Accountant_Files { get; set; }
        public DbSet<t_Accreditation_Types> t_Accreditation_Types { get; set; }
        public DbSet<t_Accreditations> t_Accreditations { get; set; }
        public DbSet<t_Alarm_Configurations> t_Alarm_Configurations { get; set; }
        public DbSet<t_Alarm_Warning> t_Alarm_Warning { get; set; }
        public DbSet<t_Alarms> t_Alarms { get; set; }
        public DbSet<t_BillingHistory> t_BillingHistory { get; set; }
        public DbSet<t_Books> t_Books { get; set; }
        public DbSet<t_Channel_Configurations> t_Channel_Configurations { get; set; }
        public DbSet<t_Consumers> t_Consumers { get; set; }
        public DbSet<t_Currency> t_Currency { get; set; }
        public DbSet<t_Data_Complexes> t_Data_Complexes { get; set; }
        public DbSet<t_DisplayGroups> t_DisplayGroups { get; set; }
        public DbSet<t_Emails> t_Emails { get; set; }
        public DbSet<t_Function> t_Function { get; set; }
        public DbSet<t_Language> t_Language { get; set; }
        public DbSet<t_LanguageTranslate> t_LanguageTranslate { get; set; }
        public DbSet<t_Logger_Configurations> t_Logger_Configurations { get; set; }
        public DbSet<t_Logger_Files> t_Logger_Files { get; set; }
        public DbSet<t_Logger_Histories> t_Logger_Histories { get; set; }
        public DbSet<t_Loggers> t_Loggers { get; set; }
        public DbSet<t_Manual_Phumy> t_Manual_Phumy { get; set; }
        public DbSet<t_Meter_Files> t_Meter_Files { get; set; }
        public DbSet<t_Meter_Histories> t_Meter_Histories { get; set; }
        public DbSet<t_Meters> t_Meters { get; set; }
        public DbSet<t_MeterSetupHistories> t_MeterSetupHistories { get; set; }
        public DbSet<t_Project_Manage> t_Project_Manage { get; set; }
        public DbSet<t_Reading> t_Reading { get; set; }
        public DbSet<t_RoleFunction> t_RoleFunction { get; set; }
        public DbSet<t_Roles> t_Roles { get; set; }
        public DbSet<t_Site_Files> t_Site_Files { get; set; }
        public DbSet<t_Sites> t_Sites { get; set; }
        public DbSet<t_SiteSetupHistories> t_SiteSetupHistories { get; set; }
        public DbSet<t_Staffs> t_Staffs { get; set; }
        public DbSet<t_SysParam> t_SysParam { get; set; }
        public DbSet<t_TaxCode> t_TaxCode { get; set; }
        public DbSet<t_Transmitter_Histories> t_Transmitter_Histories { get; set; }
        public DbSet<t_Transmitters> t_Transmitters { get; set; }
        public DbSet<t_UnitCode> t_UnitCode { get; set; }
        public DbSet<t_UnitCost> t_UnitCost { get; set; }
        public DbSet<t_Units> t_Units { get; set; }
        public DbSet<t_Users> t_Users { get; set; }
        public DbSet<t_UsingDiary> t_UsingDiary { get; set; }
        public DbSet<t_WasteWaterPercent> t_WasteWaterPercent { get; set; }
        public DbSet<tbl_ClockRecord> tbl_ClockRecord { get; set; }
        public DbSet<tbl_ClockRecord_History> tbl_ClockRecord_History { get; set; }
        public DbSet<tbl_ClockRecord_Mobile> tbl_ClockRecord_Mobile { get; set; }
        public DbSet<tbl_ClockRecordRoute> tbl_ClockRecordRoute { get; set; }
        public DbSet<tbl_ClockRepair> tbl_ClockRepair { get; set; }
        public DbSet<tbl_ClockRepairContent> tbl_ClockRepairContent { get; set; }
        public DbSet<tbl_ClockType> tbl_ClockType { get; set; }
        public DbSet<tbl_Contract> tbl_Contract { get; set; }
        public DbSet<tbl_Customer> tbl_Customer { get; set; }
        public DbSet<tbl_CustomerRoute> tbl_CustomerRoute { get; set; }
        public DbSet<tbl_CustomerType> tbl_CustomerType { get; set; }
        public DbSet<tbl_Employee> tbl_Employee { get; set; }
        public DbSet<tbl_EmployeeRoute> tbl_EmployeeRoute { get; set; }
        public DbSet<tbl_MobileAdmin> tbl_MobileAdmin { get; set; }
        public DbSet<tbl_Period> tbl_Period { get; set; }
        public DbSet<tbl_Register> tbl_Register { get; set; }
        public DbSet<tbl_Route> tbl_Route { get; set; }
        public DbSet<tbl_Status> tbl_Status { get; set; }
        public DbSet<tbl_UpdateClockSeries> tbl_UpdateClockSeries { get; set; }
        public DbSet<tbl_Zone> tbl_Zone { get; set; }
        public DbSet<temp_Location> temp_Location { get; set; }
        public DbSet<test_1990> test_1990 { get; set; }
        public DbSet<t_Device_Status> t_Device_Status { get; set; }
        public DbSet<t_Project_Progress> t_Project_Progress { get; set; }
        public DbSet<t_Site_Availabilities> t_Site_Availabilities { get; set; }
        public DbSet<t_Site_Status> t_Site_Status { get; set; }
    
        public virtual int CustomSearch(string search)
        {
            var searchParameter = search != null ?
                new ObjectParameter("search", search) :
                new ObjectParameter("search", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CustomSearch", searchParameter);
        }
    
        public virtual int DataInsert(string tName)
        {
            var tNameParameter = tName != null ?
                new ObjectParameter("TName", tName) :
                new ObjectParameter("TName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DataInsert", tNameParameter);
        }
    
        public virtual int DataXMLInsert()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DataXMLInsert");
        }
    
        public virtual int delete_complexdata(string loggerId)
        {
            var loggerIdParameter = loggerId != null ?
                new ObjectParameter("LoggerId", loggerId) :
                new ObjectParameter("LoggerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("delete_complexdata", loggerIdParameter);
        }
    
        public virtual int p_Calculate_One_Site_Daily_Output(string siteId, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Calculate_One_Site_Daily_Output", siteIdParameter, startParameter, endParameter);
        }
    
        public virtual int p_Calculate_One_Site_Hourly_Output(string siteId, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Calculate_One_Site_Hourly_Output", siteIdParameter, startParameter, endParameter);
        }
    
        public virtual int p_Calculate_One_Site_Monthly_Output(string siteId, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Calculate_One_Site_Monthly_Output", siteIdParameter, startParameter, endParameter);
        }
    
        public virtual int p_Calculate_One_Site_Yearly_Output(string siteId, Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Calculate_One_Site_Yearly_Output", siteIdParameter, startParameter, endParameter);
        }
    
        public virtual int p_Channel_Configuration()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Channel_Configuration");
        }
    
        public virtual int p_ComplexData_Select_Faster()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_Faster");
        }
    
        public virtual int p_ComplexData_Select_For_Consumer(string consumerId)
        {
            var consumerIdParameter = consumerId != null ?
                new ObjectParameter("ConsumerId", consumerId) :
                new ObjectParameter("ConsumerId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_For_Consumer", consumerIdParameter);
        }
    
        public virtual int p_ComplexData_Select_For_Site(string siteId)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_For_Site", siteIdParameter);
        }
    
        public virtual int p_ComplexData_Select_For_Staff(string staffId)
        {
            var staffIdParameter = staffId != null ?
                new ObjectParameter("StaffId", staffId) :
                new ObjectParameter("StaffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_ComplexData_Select_For_Staff", staffIdParameter);
        }
    
        public virtual int p_Create_Data_Table(string channelId)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Create_Data_Table", channelIdParameter);
        }
    
        public virtual int p_Data_Logger_Daily(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Daily", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Data_Logger_Get(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Get", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Data_Logger_Get_Alarm(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Get_Alarm", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Data_Logger_Hourly(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Hourly", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Data_Logger_Monthly(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Monthly", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Data_Logger_Yearly(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_Logger_Yearly", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Data_ManualPhuMy_Get(string siteId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var siteIdParameter = siteId != null ?
                new ObjectParameter("SiteId", siteId) :
                new ObjectParameter("SiteId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Data_ManualPhuMy_Get", siteIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Drop_Data_Table(string channelId)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("channelId", channelId) :
                new ObjectParameter("channelId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Drop_Data_Table", channelIdParameter);
        }
    
        public virtual ObjectResult<p_GetClockRecordSites_Result> p_GetClockRecordSites(string consumerId, string staffId)
        {
            var consumerIdParameter = consumerId != null ?
                new ObjectParameter("consumerId", consumerId) :
                new ObjectParameter("consumerId", typeof(string));
    
            var staffIdParameter = staffId != null ?
                new ObjectParameter("staffId", staffId) :
                new ObjectParameter("staffId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetClockRecordSites_Result>("p_GetClockRecordSites", consumerIdParameter, staffIdParameter);
        }
    
        public virtual ObjectResult<p_GetClockRecordSitesByEmployee_Result> p_GetClockRecordSitesByEmployee(string employeeCode, string routeCode)
        {
            var employeeCodeParameter = employeeCode != null ?
                new ObjectParameter("employeeCode", employeeCode) :
                new ObjectParameter("employeeCode", typeof(string));
    
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("routeCode", routeCode) :
                new ObjectParameter("routeCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetClockRecordSitesByEmployee_Result>("p_GetClockRecordSitesByEmployee", employeeCodeParameter, routeCodeParameter);
        }
    
        public virtual ObjectResult<p_GetEmployeeRouter_Result> p_GetEmployeeRouter()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_GetEmployeeRouter_Result>("p_GetEmployeeRouter");
        }
    
        public virtual int p_Index_Logger_Get(string channelId, Nullable<System.DateTime> startDate, Nullable<System.DateTime> endDate)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var startDateParameter = startDate.HasValue ?
                new ObjectParameter("StartDate", startDate) :
                new ObjectParameter("StartDate", typeof(System.DateTime));
    
            var endDateParameter = endDate.HasValue ?
                new ObjectParameter("EndDate", endDate) :
                new ObjectParameter("EndDate", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Index_Logger_Get", channelIdParameter, startDateParameter, endDateParameter);
        }
    
        public virtual int p_Insert_ManualData_Table(string channelId, string name, Nullable<double> salary)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            var nameParameter = name != null ?
                new ObjectParameter("Name", name) :
                new ObjectParameter("Name", typeof(string));
    
            var salaryParameter = salary.HasValue ?
                new ObjectParameter("Salary", salary) :
                new ObjectParameter("Salary", typeof(double));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Insert_ManualData_Table", channelIdParameter, nameParameter, salaryParameter);
        }
    
        public virtual int p_Manual_Logger_Get(string channelId)
        {
            var channelIdParameter = channelId != null ?
                new ObjectParameter("ChannelId", channelId) :
                new ObjectParameter("ChannelId", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Manual_Logger_Get", channelIdParameter);
        }
    
        public virtual ObjectResult<p_Our_Sites_Logger_As_Scada_Database_Result> p_Our_Sites_Logger_As_Scada_Database()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<p_Our_Sites_Logger_As_Scada_Database_Result>("p_Our_Sites_Logger_As_Scada_Database");
        }
    
        public virtual int p_Press_Get(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Get", startParameter, endParameter);
        }
    
        public virtual int p_Press_Get_2015(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("start", start) :
                new ObjectParameter("start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("end", end) :
                new ObjectParameter("end", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Get_2015", startParameter, endParameter);
        }
    
        public virtual int p_Press_Getw(Nullable<System.DateTime> start, Nullable<System.DateTime> end, string cboSites)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            var cboSitesParameter = cboSites != null ?
                new ObjectParameter("cboSites", cboSites) :
                new ObjectParameter("cboSites", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Getw", startParameter, endParameter, cboSitesParameter);
        }
    
        public virtual int p_Press_Getw_Staff(Nullable<System.DateTime> start, Nullable<System.DateTime> end)
        {
            var startParameter = start.HasValue ?
                new ObjectParameter("Start", start) :
                new ObjectParameter("Start", typeof(System.DateTime));
    
            var endParameter = end.HasValue ?
                new ObjectParameter("End", end) :
                new ObjectParameter("End", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Press_Getw_Staff", startParameter, endParameter);
        }
    
        public virtual int p_Reading_Report(Nullable<System.DateTime> period, string zoneCode, string consumerId, string routeCode)
        {
            var periodParameter = period.HasValue ?
                new ObjectParameter("period", period) :
                new ObjectParameter("period", typeof(System.DateTime));
    
            var zoneCodeParameter = zoneCode != null ?
                new ObjectParameter("zoneCode", zoneCode) :
                new ObjectParameter("zoneCode", typeof(string));
    
            var consumerIdParameter = consumerId != null ?
                new ObjectParameter("consumerId", consumerId) :
                new ObjectParameter("consumerId", typeof(string));
    
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("routeCode", routeCode) :
                new ObjectParameter("routeCode", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("p_Reading_Report", periodParameter, zoneCodeParameter, consumerIdParameter, routeCodeParameter);
        }
    
        public virtual int ProductsAccessXMLInsertDataComplex(string validXMLInput)
        {
            var validXMLInputParameter = validXMLInput != null ?
                new ObjectParameter("ValidXMLInput", validXMLInput) :
                new ObjectParameter("ValidXMLInput", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ProductsAccessXMLInsertDataComplex", validXMLInputParameter);
        }
    
        public virtual ObjectResult<Service_GetClockRecordByRoute_Result> Service_GetClockRecordByRoute(string routeCode, string userName, string imei)
        {
            var routeCodeParameter = routeCode != null ?
                new ObjectParameter("RouteCode", routeCode) :
                new ObjectParameter("RouteCode", typeof(string));
    
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            var imeiParameter = imei != null ?
                new ObjectParameter("Imei", imei) :
                new ObjectParameter("Imei", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Service_GetClockRecordByRoute_Result>("Service_GetClockRecordByRoute", routeCodeParameter, userNameParameter, imeiParameter);
        }
    }
}
