//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class KHACHHANG
    {
        public KHACHHANG()
        {
            this.TIEUTHUs = new HashSet<TIEUTHU>();
        }
    
        public string IDKH { get; set; }
        public string MADP { get; set; }
        public string DUONGPHU { get; set; }
        public string MADB { get; set; }
        public string MADBCU { get; set; }
        public Nullable<int> STT { get; set; }
        public string MAMDSD { get; set; }
        public string MAKV { get; set; }
        public Nullable<int> NHOMKV { get; set; }
        public string TENKH { get; set; }
        public string SONHA { get; set; }
        public string MAPHUONG { get; set; }
        public string SDT { get; set; }
        public string CMND { get; set; }
        public string NOICAPCM { get; set; }
        public string MADDK { get; set; }
        public string MST { get; set; }
        public string STK { get; set; }
        public string MALKH { get; set; }
        public string MAHTTT { get; set; }
        public Nullable<bool> ISDINHMUC { get; set; }
        public Nullable<int> SONK { get; set; }
        public Nullable<int> M3KHOAN { get; set; }
        public Nullable<int> THUEBAO { get; set; }
        public string MALDH { get; set; }
        public string THUYLK { get; set; }
        public string MADH { get; set; }
        public Nullable<System.DateTime> NGAYHT { get; set; }
        public Nullable<System.DateTime> NGAYTHAYDH { get; set; }
        public Nullable<System.DateTime> NGAYCUP { get; set; }
        public Nullable<int> SLANTHAYDH { get; set; }
        public string TTSD { get; set; }
        public Nullable<bool> KOPHINT { get; set; }
        public Nullable<bool> KOVAT { get; set; }
        public Nullable<bool> TTHD { get; set; }
        public string TTHD_TENKH { get; set; }
        public string TTHD_DIACHI { get; set; }
        public string MATT { get; set; }
        public Nullable<System.DateTime> KYKHAITHAC { get; set; }
        public Nullable<decimal> CHISODAU { get; set; }
        public Nullable<decimal> CHISOCUOI { get; set; }
        public string CHANLE { get; set; }
        public Nullable<decimal> SODU { get; set; }
        public Nullable<bool> ISXOABO { get; set; }
        public Nullable<System.DateTime> NGAYXOA { get; set; }
        public string MANVXOA { get; set; }
        public Nullable<bool> ISNUOCTHO { get; set; }
        public Nullable<decimal> GIAHD { get; set; }
        public Nullable<bool> ISKHDB { get; set; }
        public string SORT { get; set; }
        public Nullable<System.DateTime> NGAYHETHANDH { get; set; }
        public string MAVUNG { get; set; }
    
        public virtual ICollection<TIEUTHU> TIEUTHUs { get; set; }
    }
}
