//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHUONG
    {
        public PHUONG()
        {
            this.DUONGPHOes = new HashSet<DUONGPHO>();
            this.KHACHHANGs = new HashSet<KHACHHANG>();
        }
    
        public string MAPHUONG { get; set; }
        public string TENPHUONG { get; set; }
        public string MAKV { get; set; }
        public Nullable<int> THUTUIN { get; set; }
    
        public virtual ICollection<DUONGPHO> DUONGPHOes { get; set; }
        public virtual ICollection<KHACHHANG> KHACHHANGs { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
    }
}
