//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Accreditation_Types
    {
        public t_Accreditation_Types()
        {
            this.t_Accreditations = new HashSet<t_Accreditations>();
        }
    
        public string Type { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<t_Accreditations> t_Accreditations { get; set; }
    }
}
