//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Accountant_Files
    {
        public string FileName { get; set; }
        public string Extension { get; set; }
        public Nullable<double> Size { get; set; }
        public Nullable<System.DateTime> UploadDate { get; set; }
        public string UploadBy { get; set; }
        public Nullable<long> ProjectId { get; set; }
        public string Description { get; set; }
    }
}
