//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_BillingHistory
    {
        public string BookName { get; set; }
        public Nullable<System.DateTime> Period { get; set; }
        public Nullable<int> ref_count { get; set; }
        public string SO_REF { get; set; }
        public int SO_LINE { get; set; }
        public string SO_DATE { get; set; }
        public string SERI_OF_WATER_METER { get; set; }
        public string CUS_NAME { get; set; }
        public string ITEM_CODE { get; set; }
        public string CUS_CODE { get; set; }
        public string PROJECT_PHASE { get; set; }
        public string UNIT_CODE { get; set; }
        public string TAX_CODE { get; set; }
        public string DESCRIPTION_VN { get; set; }
        public string DESCRIPTION_EN { get; set; }
        public Nullable<double> FIRST_INDEX { get; set; }
        public Nullable<double> LAST_INDEX { get; set; }
        public Nullable<decimal> QUANTITY { get; set; }
        public Nullable<decimal> UNIT_PRICE { get; set; }
        public string CURRENCY { get; set; }
        public Nullable<decimal> TYGIA { get; set; }
        public string DU_PHONG_2 { get; set; }
        public string DU_PHONG_3 { get; set; }
        public string DU_PHONG_4 { get; set; }
        public string DU_PHONG_5 { get; set; }
        public string DU_PHONG_6 { get; set; }
        public string DU_PHONG_7 { get; set; }
        public string DU_PHONG_8 { get; set; }
        public string DU_PHONG_9 { get; set; }
        public string DU_PHONG_10 { get; set; }
    }
}
