//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Books
    {
        public int BookId { get; set; }
        public string BookName { get; set; }
        public Nullable<int> ConfirmDay { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Disable { get; set; }
    }
}
