//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Consumers
    {
        public string ConsumerId { get; set; }
        public Nullable<byte> Zoom { get; set; }
        public string Description { get; set; }
        public Nullable<int> SetDefault { get; set; }
        public string Acronym { get; set; }
        public string Address { get; set; }
        public string Email { get; set; }
        public string Fax { get; set; }
        public string Phone { get; set; }
        public string Contact { get; set; }
        public string Career { get; set; }
        public string DMA { get; set; }
        public long Id { get; set; }
    }
}
