//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Currency
    {
        public string CurrencyCode { get; set; }
        public string Currency { get; set; }
        public Nullable<double> CashCost { get; set; }
        public Nullable<double> TransferCost { get; set; }
        public Nullable<double> SaleCost { get; set; }
    }
}
