//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_DisplayGroups
    {
        public t_DisplayGroups()
        {
            this.t_Sites = new HashSet<t_Sites>();
        }
    
        public string Group { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<t_Sites> t_Sites { get; set; }
    }
}
