//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Manual_Phumy
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<double> Anh_Vy_D200 { get; set; }
        public Nullable<double> Chau_Duc_D600 { get; set; }
        public Nullable<double> Chau_Duc_D800 { get; set; }
        public Nullable<double> China_Steel { get; set; }
        public Nullable<double> DHK_Chau_Duc { get; set; }
        public Nullable<double> DHK_Ngoai_KCN { get; set; }
        public Nullable<double> DHK_Toc_Tien { get; set; }
        public Nullable<double> DHK_TT_Cap_PM1 { get; set; }
        public Nullable<double> KCN_B1_Tien_Hung { get; set; }
        public Nullable<double> KCN_Go_Dau_DN300 { get; set; }
        public Nullable<double> KCN_MXA_2_1_DN300 { get; set; }
        public Nullable<double> KCN_MXA_2_2_DN200 { get; set; }
        public Nullable<double> KCN_MXA_DN300 { get; set; }
        public Nullable<double> KCN_MXA_DN300_2 { get; set; }
        public Nullable<double> KCN_Phu_My_3 { get; set; }
        public Nullable<double> KCN_Phu_My_I_DN300_1 { get; set; }
        public Nullable<double> KCN_Phu_My_I_DN300_2 { get; set; }
        public Nullable<double> KCN_Phu_My_I_DN300_3 { get; set; }
        public Nullable<double> Long_Son { get; set; }
        public Nullable<double> NM_Giay_MX { get; set; }
        public Nullable<double> POSCO_DN400 { get; set; }
        public Nullable<double> POSCO_SS { get; set; }
        public Nullable<double> TDC_44HA { get; set; }
        public Nullable<double> TTXH_D200_1 { get; set; }
        public Nullable<double> TTXH_D200_2 { get; set; }
        public Nullable<double> TTXH_D50 { get; set; }
        public Nullable<double> Tuyen_Duoi_D400 { get; set; }
        public Nullable<double> Tuyen_tren_D400 { get; set; }
    }
}
