//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_MeterSetupHistories
    {
        public int ID { get; set; }
        public string MeterSerial { get; set; }
        public string SiteId { get; set; }
        public string Site { get; set; }
        public string ConsumerId { get; set; }
        public string Consumer { get; set; }
        public string Status { get; set; }
        public string Action { get; set; }
        public System.DateTime TimeStamp { get; set; }
    }
}
