//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Project_Progress
    {
        public long ProjectId { get; set; }
        public Nullable<System.DateTime> NgayDaChapThuan { get; set; }
        public Nullable<System.DateTime> NgayChoDauNoi { get; set; }
        public Nullable<System.DateTime> NgayTienHanhDauNoi { get; set; }
        public Nullable<System.DateTime> NgayKeToan { get; set; }
        public Nullable<System.DateTime> NgayHSNT { get; set; }
        public Nullable<System.DateTime> NgayHT { get; set; }
    }
}
