//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Project_Manage
    {
        public long ProjectId { get; set; }
        public string ConsumerId { get; set; }
        public string SiteId { get; set; }
        public string DisplayGroup { get; set; }
        public string OldMeterSerial { get; set; }
        public string NewMeterSerial { get; set; }
        public string StaffId { get; set; }
        public Nullable<System.DateTime> TimeAssign { get; set; }
        public Nullable<System.DateTime> TimeExpected { get; set; }
        public string ProjectType { get; set; }
        public string Notes { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> TimeCompleted { get; set; }
        public string UnitCode { get; set; }
        public Nullable<double> RegisProduction { get; set; }
    }
}
