//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Roles
    {
        public t_Roles()
        {
            this.t_Users = new HashSet<t_Users>();
        }
    
        public string Role { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<t_Users> t_Users { get; set; }
    }
}
