//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_Staffs
    {
        public t_Staffs()
        {
            this.t_Users = new HashSet<t_Users>();
        }
    
        public string StaffId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string TelephoneNumber { get; set; }
        public int Id { get; set; }
        public string Sites { get; set; }
    
        public virtual ICollection<t_Users> t_Users { get; set; }
    }
}
