//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UnitCode
    {
        public string UnitCode { get; set; }
        public string ConsumerId { get; set; }
        public string Description { get; set; }
        public Nullable<double> Threshold { get; set; }
        public string OverloadUnitCost { get; set; }
        public string ComplexStringWTR { get; set; }
        public string ComplexStringSEW { get; set; }
        public bool IsSeparateInvoice { get; set; }
    }
}
