//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_UsingDiary
    {
        public string Username { get; set; }
        public string Role { get; set; }
        public string FunctionName { get; set; }
        public System.DateTime TimeStamp { get; set; }
        public string Url { get; set; }
    }
}
