//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Employee
    {
        public int EmployeeID { get; set; }
        public string EmployeeCode { get; set; }
        public string Password { get; set; }
        public string EmployeeFullName { get; set; }
        public string EmployeePhone { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsMobile { get; set; }
        public string Imei1 { get; set; }
        public string Imei2 { get; set; }
        public string PrinterID { get; set; }
    }
}
