//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Register
    {
        public long RegisterID { get; set; }
        public string RegisterCode { get; set; }
        public long CustomerID { get; set; }
        public string StatusCode { get; set; }
        public string Notes { get; set; }
        public int RegisterType { get; set; }
        public string BuildAddress { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> ApproveDate { get; set; }
        public string CreateUser { get; set; }
        public string ContractStatus { get; set; }
        public string DesignImageSource { get; set; }
        public string LetterApproveSource { get; set; }
        public string FormRegisterSouce { get; set; }
        public Nullable<System.DateTime> UserModifyDate { get; set; }
        public string UserModifyName { get; set; }
        public string RepresentativeName { get; set; }
        public string TradeTitle { get; set; }
    }
}
