//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClockRecord_Mobile
    {
        public System.DateTime Period { get; set; }
        public long ContractID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string StatusCode { get; set; }
        public Nullable<long> LastNumber { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
        public Nullable<int> InputTime { get; set; }
        public string Notes { get; set; }
        public string User_Input { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
        public string ImageSource { get; set; }
        public string ImageName { get; set; }
    }
}
