//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClockRepair
    {
        public long RepairID { get; set; }
        public long ContractID { get; set; }
        public int ContentID { get; set; }
        public string Descr { get; set; }
        public Nullable<System.DateTime> GiveDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
        public string ClockCode { get; set; }
        public Nullable<int> ClockTypeID { get; set; }
        public Nullable<long> NewFirstNumber { get; set; }
        public Nullable<long> OldLastNumber { get; set; }
        public string Cause { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    }
}
