//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClockType
    {
        public int ClockTypeID { get; set; }
        public string ClockTypeCode { get; set; }
        public string ClockTypeDescr { get; set; }
        public Nullable<int> Size { get; set; }
    }
}
