//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClockRecord
    {
        public int ClockRecordID { get; set; }
        public long ContractID { get; set; }
        public int RouteID { get; set; }
        public System.DateTime Period { get; set; }
        public Nullable<long> FirstNumber { get; set; }
        public Nullable<long> LastNumber { get; set; }
        public Nullable<System.DateTime> FirstDate { get; set; }
        public Nullable<System.DateTime> LastDate { get; set; }
        public Nullable<long> UsageNumber { get; set; }
        public Nullable<double> ArrearsQuantity { get; set; }
        public string StatusCode { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateUser { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
        public Nullable<System.DateTime> RecordTime { get; set; }
        public Nullable<int> InputTime { get; set; }
        public string Notes { get; set; }
        public string User_Input { get; set; }
        public Nullable<long> LastNumber_Mobile { get; set; }
        public string StatusCode_Mobile { get; set; }
        public string LastFirstStatusCode { get; set; }
        public Nullable<long> LastFirstUsageNumber { get; set; }
        public string LastSecondStatusCode { get; set; }
        public Nullable<long> LastSecondUsageNumber { get; set; }
        public string LastThirdStatusCode { get; set; }
        public Nullable<long> LastThirdUsageNumber { get; set; }
        public Nullable<long> AvgUseNumber { get; set; }
        public Nullable<double> Lon { get; set; }
        public Nullable<double> Lat { get; set; }
        public Nullable<short> StatusLockBook { get; set; }
        public string ImageSource { get; set; }
        public string ImageName { get; set; }
        public Nullable<bool> LockedStatus { get; set; }
        public Nullable<int> BookId { get; set; }
    }
}
