//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_ClockRepairContent
    {
        public int ContentID { get; set; }
        public string ContentCode { get; set; }
        public string ContentName { get; set; }
        public string ContentDescr { get; set; }
    }
}
