//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_UpdateClockSeries
    {
        public int ApplyID { get; set; }
        public int ContractID { get; set; }
        public string ClockCode { get; set; }
        public Nullable<System.DateTime> ApplyDate { get; set; }
        public Nullable<long> FirstNum { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public string ModifyUser { get; set; }
    }
}
