//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Status
    {
        public int StatusID { get; set; }
        public string StatusCode { get; set; }
        public string StatusName { get; set; }
        public string StatusDescr { get; set; }
        public string StatusType { get; set; }
        public Nullable<short> IsPublish { get; set; }
        public Nullable<int> No { get; set; }
    }
}
