//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConvertDataKienGiang
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIEUTHU
    {
        public string IDKH { get; set; }
        public int NAM { get; set; }
        public int THANG { get; set; }
        public Nullable<int> STT { get; set; }
        public string TENKH { get; set; }
        public string SONHA { get; set; }
        public string MAKV { get; set; }
        public string MADP { get; set; }
        public string DUONGPHU { get; set; }
        public string MADB { get; set; }
        public string MADBCU { get; set; }
        public string SODB { get; set; }
        public string MAPHUONG { get; set; }
        public Nullable<decimal> CHISODAU { get; set; }
        public Nullable<decimal> CHISOCUOI { get; set; }
        public Nullable<decimal> KLTIEUTHU { get; set; }
        public string MAMDSD { get; set; }
        public string MALKH { get; set; }
        public string MACQTT { get; set; }
        public Nullable<bool> ISDINHMUC { get; set; }
        public Nullable<int> SONK { get; set; }
        public Nullable<int> M3KHOAN { get; set; }
        public Nullable<int> THUEBAO { get; set; }
        public Nullable<int> BAOTRI { get; set; }
        public string TTSD { get; set; }
        public Nullable<bool> KOPHINT { get; set; }
        public Nullable<bool> KOVAT { get; set; }
        public string TTHAIGHI { get; set; }
        public string THBT { get; set; }
        public Nullable<decimal> TIENNUOC { get; set; }
        public Nullable<decimal> TIENPHI { get; set; }
        public Nullable<decimal> TIENTHUE { get; set; }
        public Nullable<decimal> TONGTIEN { get; set; }
        public Nullable<int> M3SH { get; set; }
        public Nullable<decimal> GIASH { get; set; }
        public Nullable<decimal> TNUOCSH { get; set; }
        public Nullable<decimal> THUESH { get; set; }
        public Nullable<decimal> PHISH { get; set; }
        public Nullable<int> M3SX { get; set; }
        public Nullable<decimal> GIASX { get; set; }
        public Nullable<decimal> TNUOCSX { get; set; }
        public Nullable<decimal> THUESX { get; set; }
        public Nullable<decimal> PHISX { get; set; }
        public Nullable<int> M3KD { get; set; }
        public Nullable<decimal> GIAKD { get; set; }
        public Nullable<decimal> TNUOCKD { get; set; }
        public Nullable<decimal> THUEKD { get; set; }
        public Nullable<decimal> PHIKD { get; set; }
        public Nullable<int> M3HD { get; set; }
        public Nullable<decimal> GIAHD { get; set; }
        public Nullable<decimal> TNUOCHD { get; set; }
        public Nullable<decimal> THUEHD { get; set; }
        public Nullable<decimal> PHIHD { get; set; }
        public Nullable<decimal> CHISODAU_TT { get; set; }
        public Nullable<decimal> CHISOCUOI_TT { get; set; }
        public Nullable<decimal> KLTIEUTHU_TT { get; set; }
        public Nullable<decimal> TONGTIEN_TT { get; set; }
        public string MAHTTT { get; set; }
        public Nullable<bool> INHD { get; set; }
        public Nullable<bool> ISGCS { get; set; }
        public string GHICHU_CS { get; set; }
        public string MANVN_CS { get; set; }
        public Nullable<System.DateTime> NGAYNHAP_CS { get; set; }
        public Nullable<bool> HETNO { get; set; }
        public Nullable<bool> THUTQ { get; set; }
        public Nullable<bool> TON { get; set; }
        public Nullable<System.DateTime> NGAYCN { get; set; }
        public string MANVNHAPCN { get; set; }
        public Nullable<System.DateTime> NGAYNHAPCN { get; set; }
        public string GHICHUCN { get; set; }
        public string SOPHIEUCN { get; set; }
        public Nullable<decimal> TIENNO { get; set; }
        public Nullable<bool> ISTRACHAM { get; set; }
        public Nullable<bool> CHIADOITUONG { get; set; }
        public string SOSERIALHD { get; set; }
        public Nullable<bool> ISXOABO { get; set; }
        public Nullable<decimal> GIAPHI { get; set; }
        public Nullable<bool> ISNUOCTHO { get; set; }
        public Nullable<int> PTPHITHUEBAO { get; set; }
        public Nullable<int> PTTHUE { get; set; }
        public Nullable<bool> ISKHDB { get; set; }
        public string MAVUNG { get; set; }
        public Nullable<System.DateTime> NGAYKY_DIENTU { get; set; }
        public string FILE_DIENTU { get; set; }
        public Nullable<bool> ISCOCHINHSUA_CONGNO { get; set; }
        public string SO_HOADON_DIENTU { get; set; }
        public string KYHIEU_DIENTU { get; set; }
        public Nullable<bool> ISCHOPHEPTAISOM { get; set; }
        public Nullable<bool> ISKHACHHANGDATAIHOADON { get; set; }
        public Nullable<System.DateTime> NGAYKHACHHANGTAIHOADON { get; set; }
        public Nullable<bool> IS_CHAN_KHONGCHOTAI_HOADON { get; set; }
        public Nullable<bool> ISPHATSINH_HDDIENTU { get; set; }
        public Nullable<bool> ISGIATN { get; set; }
    
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual DUONGPHO DUONGPHO { get; set; }
        public virtual KHUVUC KHUVUC { get; set; }
    }
}
